version: '3.8'
services:
  api:
    env_file: ./api/.env
    build: api
    container_name: discount-api
    ports:
        - 8080:8000
    volumes:
        - ./api:/api
    depends_on:
      - db
    networks:
      - app

  ui:
    build: ui
    container_name: discount-ui
    ports:
        - 3000:8080
    volumes:
      - ./ui/src:/ui/src
    depends_on:
      - db
      - api
    networks:
      - app

  db:
    image: postgres:13
    container_name: discount-pgdb
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  db_data:

networks:
  app: