name: Laravel

on:
  push:
    branches:
      - "main"
      - "feature/ui/**"
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      working-directory: ./api
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ./api
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      working-directory: ./api
      run: php artisan key:generate
    - name: Run tests
      working-directory: ./api
      run: php artisan test
    - name: Run lint
      working-directory: ./api
      run: ./vendor/bin/tlint lint
